// Países ISO 3166-1 — usados para selects y filtros en toda la app.
export interface MasterCountry {
  code: string; // ISO 3166-1 alpha-2
  code3: string; // ISO 3166-1 alpha-3
  name: string;
  nameEn: string;
  region: string;
}

export const MASTER_COUNTRIES: MasterCountry[] = [
  // Europa
  { code: "AD", code3: "AND", name: "Andorra", nameEn: "Andorra", region: "Europa" },
  { code: "AL", code3: "ALB", name: "Albania", nameEn: "Albania", region: "Europa" },
  { code: "AT", code3: "AUT", name: "Austria", nameEn: "Austria", region: "Europa" },
  { code: "BA", code3: "BIH", name: "Bosnia y Herzegovina", nameEn: "Bosnia and Herzegovina", region: "Europa" },
  { code: "BE", code3: "BEL", name: "Bélgica", nameEn: "Belgium", region: "Europa" },
  { code: "BG", code3: "BGR", name: "Bulgaria", nameEn: "Bulgaria", region: "Europa" },
  { code: "BY", code3: "BLR", name: "Bielorrusia", nameEn: "Belarus", region: "Europa" },
  { code: "CH", code3: "CHE", name: "Suiza", nameEn: "Switzerland", region: "Europa" },
  { code: "CY", code3: "CYP", name: "Chipre", nameEn: "Cyprus", region: "Europa" },
  { code: "CZ", code3: "CZE", name: "Chequia", nameEn: "Czech Republic", region: "Europa" },
  { code: "DE", code3: "DEU", name: "Alemania", nameEn: "Germany", region: "Europa" },
  { code: "DK", code3: "DNK", name: "Dinamarca", nameEn: "Denmark", region: "Europa" },
  { code: "EE", code3: "EST", name: "Estonia", nameEn: "Estonia", region: "Europa" },
  { code: "ES", code3: "ESP", name: "España", nameEn: "Spain", region: "Europa" },
  { code: "FI", code3: "FIN", name: "Finlandia", nameEn: "Finland", region: "Europa" },
  { code: "FR", code3: "FRA", name: "Francia", nameEn: "France", region: "Europa" },
  { code: "GB", code3: "GBR", name: "Reino Unido", nameEn: "United Kingdom", region: "Europa" },
  { code: "GR", code3: "GRC", name: "Grecia", nameEn: "Greece", region: "Europa" },
  { code: "HR", code3: "HRV", name: "Croacia", nameEn: "Croatia", region: "Europa" },
  { code: "HU", code3: "HUN", name: "Hungría", nameEn: "Hungary", region: "Europa" },
  { code: "IE", code3: "IRL", name: "Irlanda", nameEn: "Ireland", region: "Europa" },
  { code: "IS", code3: "ISL", name: "Islandia", nameEn: "Iceland", region: "Europa" },
  { code: "IT", code3: "ITA", name: "Italia", nameEn: "Italy", region: "Europa" },
  { code: "LI", code3: "LIE", name: "Liechtenstein", nameEn: "Liechtenstein", region: "Europa" },
  { code: "LT", code3: "LTU", name: "Lituania", nameEn: "Lithuania", region: "Europa" },
  { code: "LU", code3: "LUX", name: "Luxemburgo", nameEn: "Luxembourg", region: "Europa" },
  { code: "LV", code3: "LVA", name: "Letonia", nameEn: "Latvia", region: "Europa" },
  { code: "MC", code3: "MCO", name: "Mónaco", nameEn: "Monaco", region: "Europa" },
  { code: "MD", code3: "MDA", name: "Moldavia", nameEn: "Moldova", region: "Europa" },
  { code: "ME", code3: "MNE", name: "Montenegro", nameEn: "Montenegro", region: "Europa" },
  { code: "MK", code3: "MKD", name: "Macedonia del Norte", nameEn: "North Macedonia", region: "Europa" },
  { code: "MT", code3: "MLT", name: "Malta", nameEn: "Malta", region: "Europa" },
  { code: "NL", code3: "NLD", name: "Países Bajos", nameEn: "Netherlands", region: "Europa" },
  { code: "NO", code3: "NOR", name: "Noruega", nameEn: "Norway", region: "Europa" },
  { code: "PL", code3: "POL", name: "Polonia", nameEn: "Poland", region: "Europa" },
  { code: "PT", code3: "PRT", name: "Portugal", nameEn: "Portugal", region: "Europa" },
  { code: "RO", code3: "ROU", name: "Rumanía", nameEn: "Romania", region: "Europa" },
  { code: "RS", code3: "SRB", name: "Serbia", nameEn: "Serbia", region: "Europa" },
  { code: "RU", code3: "RUS", name: "Rusia", nameEn: "Russia", region: "Europa" },
  { code: "SE", code3: "SWE", name: "Suecia", nameEn: "Sweden", region: "Europa" },
  { code: "SI", code3: "SVN", name: "Eslovenia", nameEn: "Slovenia", region: "Europa" },
  { code: "SK", code3: "SVK", name: "Eslovaquia", nameEn: "Slovakia", region: "Europa" },
  { code: "SM", code3: "SMR", name: "San Marino", nameEn: "San Marino", region: "Europa" },
  { code: "TR", code3: "TUR", name: "Türkiye", nameEn: "Turkey", region: "Europa" },
  { code: "UA", code3: "UKR", name: "Ucrania", nameEn: "Ukraine", region: "Europa" },
  // Asia
  { code: "AE", code3: "ARE", name: "Emiratos Árabes Unidos", nameEn: "United Arab Emirates", region: "Asia" },
  { code: "AF", code3: "AFG", name: "Afganistán", nameEn: "Afghanistan", region: "Asia" },
  { code: "AM", code3: "ARM", name: "Armenia", nameEn: "Armenia", region: "Asia" },
  { code: "AZ", code3: "AZE", name: "Azerbaiyán", nameEn: "Azerbaijan", region: "Asia" },
  { code: "BD", code3: "BGD", name: "Bangladés", nameEn: "Bangladesh", region: "Asia" },
  { code: "BH", code3: "BHR", name: "Baréin", nameEn: "Bahrain", region: "Asia" },
  { code: "BN", code3: "BRN", name: "Brunéi", nameEn: "Brunei", region: "Asia" },
  { code: "CN", code3: "CHN", name: "China", nameEn: "China", region: "Asia" },
  { code: "GE", code3: "GEO", name: "Georgia", nameEn: "Georgia", region: "Asia" },
  { code: "HK", code3: "HKG", name: "Hong Kong", nameEn: "Hong Kong", region: "Asia" },
  { code: "ID", code3: "IDN", name: "Indonesia", nameEn: "Indonesia", region: "Asia" },
  { code: "IL", code3: "ISR", name: "Israel", nameEn: "Israel", region: "Asia" },
  { code: "IN", code3: "IND", name: "India", nameEn: "India", region: "Asia" },
  { code: "IQ", code3: "IRQ", name: "Irak", nameEn: "Iraq", region: "Asia" },
  { code: "IR", code3: "IRN", name: "Irán", nameEn: "Iran", region: "Asia" },
  { code: "JO", code3: "JOR", name: "Jordania", nameEn: "Jordan", region: "Asia" },
  { code: "JP", code3: "JPN", name: "Japón", nameEn: "Japan", region: "Asia" },
  { code: "KH", code3: "KHM", name: "Camboya", nameEn: "Cambodia", region: "Asia" },
  { code: "KR", code3: "KOR", name: "Corea del Sur", nameEn: "South Korea", region: "Asia" },
  { code: "KW", code3: "KWT", name: "Kuwait", nameEn: "Kuwait", region: "Asia" },
  { code: "KZ", code3: "KAZ", name: "Kazajistán", nameEn: "Kazakhstan", region: "Asia" },
  { code: "LA", code3: "LAO", name: "Laos", nameEn: "Laos", region: "Asia" },
  { code: "LB", code3: "LBN", name: "Líbano", nameEn: "Lebanon", region: "Asia" },
  { code: "LK", code3: "LKA", name: "Sri Lanka", nameEn: "Sri Lanka", region: "Asia" },
  { code: "MM", code3: "MMR", name: "Myanmar", nameEn: "Myanmar", region: "Asia" },
  { code: "MN", code3: "MNG", name: "Mongolia", nameEn: "Mongolia", region: "Asia" },
  { code: "MO", code3: "MAC", name: "Macao", nameEn: "Macau", region: "Asia" },
  { code: "MY", code3: "MYS", name: "Malasia", nameEn: "Malaysia", region: "Asia" },
  { code: "NP", code3: "NPL", name: "Nepal", nameEn: "Nepal", region: "Asia" },
  { code: "OM", code3: "OMN", name: "Omán", nameEn: "Oman", region: "Asia" },
  { code: "PH", code3: "PHL", name: "Filipinas", nameEn: "Philippines", region: "Asia" },
  { code: "PK", code3: "PAK", name: "Pakistán", nameEn: "Pakistan", region: "Asia" },
  { code: "QA", code3: "QAT", name: "Catar", nameEn: "Qatar", region: "Asia" },
  { code: "SA", code3: "SAU", name: "Arabia Saudí", nameEn: "Saudi Arabia", region: "Asia" },
  { code: "SG", code3: "SGP", name: "Singapur", nameEn: "Singapore", region: "Asia" },
  { code: "TH", code3: "THA", name: "Tailandia", nameEn: "Thailand", region: "Asia" },
  { code: "TJ", code3: "TJK", name: "Tayikistán", nameEn: "Tajikistan", region: "Asia" },
  { code: "TW", code3: "TWN", name: "Taiwán", nameEn: "Taiwan", region: "Asia" },
  { code: "UZ", code3: "UZB", name: "Uzbekistán", nameEn: "Uzbekistan", region: "Asia" },
  { code: "VN", code3: "VNM", name: "Vietnam", nameEn: "Vietnam", region: "Asia" },
  { code: "YE", code3: "YEM", name: "Yemen", nameEn: "Yemen", region: "Asia" },
  // América del Norte y Central
  { code: "CA", code3: "CAN", name: "Canadá", nameEn: "Canada", region: "América" },
  { code: "CR", code3: "CRI", name: "Costa Rica", nameEn: "Costa Rica", region: "América" },
  { code: "CU", code3: "CUB", name: "Cuba", nameEn: "Cuba", region: "América" },
  { code: "DO", code3: "DOM", name: "República Dominicana", nameEn: "Dominican Republic", region: "América" },
  { code: "GT", code3: "GTM", name: "Guatemala", nameEn: "Guatemala", region: "América" },
  { code: "HN", code3: "HND", name: "Honduras", nameEn: "Honduras", region: "América" },
  { code: "MX", code3: "MEX", name: "México", nameEn: "Mexico", region: "América" },
  { code: "NI", code3: "NIC", name: "Nicaragua", nameEn: "Nicaragua", region: "América" },
  { code: "PA", code3: "PAN", name: "Panamá", nameEn: "Panama", region: "América" },
  { code: "SV", code3: "SLV", name: "El Salvador", nameEn: "El Salvador", region: "América" },
  { code: "US", code3: "USA", name: "Estados Unidos", nameEn: "United States", region: "América" },
  // América del Sur
  { code: "AR", code3: "ARG", name: "Argentina", nameEn: "Argentina", region: "América" },
  { code: "BO", code3: "BOL", name: "Bolivia", nameEn: "Bolivia", region: "América" },
  { code: "BR", code3: "BRA", name: "Brasil", nameEn: "Brazil", region: "América" },
  { code: "CL", code3: "CHL", name: "Chile", nameEn: "Chile", region: "América" },
  { code: "CO", code3: "COL", name: "Colombia", nameEn: "Colombia", region: "América" },
  { code: "EC", code3: "ECU", name: "Ecuador", nameEn: "Ecuador", region: "América" },
  { code: "PE", code3: "PER", name: "Perú", nameEn: "Peru", region: "América" },
  { code: "PY", code3: "PRY", name: "Paraguay", nameEn: "Paraguay", region: "América" },
  { code: "UY", code3: "URY", name: "Uruguay", nameEn: "Uruguay", region: "América" },
  { code: "VE", code3: "VEN", name: "Venezuela", nameEn: "Venezuela", region: "América" },
  // África
  { code: "DZ", code3: "DZA", name: "Argelia", nameEn: "Algeria", region: "África" },
  { code: "AO", code3: "AGO", name: "Angola", nameEn: "Angola", region: "África" },
  { code: "CI", code3: "CIV", name: "Costa de Marfil", nameEn: "Ivory Coast", region: "África" },
  { code: "CM", code3: "CMR", name: "Camerún", nameEn: "Cameroon", region: "África" },
  { code: "EG", code3: "EGY", name: "Egipto", nameEn: "Egypt", region: "África" },
  { code: "ET", code3: "ETH", name: "Etiopía", nameEn: "Ethiopia", region: "África" },
  { code: "GH", code3: "GHA", name: "Ghana", nameEn: "Ghana", region: "África" },
  { code: "KE", code3: "KEN", name: "Kenia", nameEn: "Kenya", region: "África" },
  { code: "LY", code3: "LBY", name: "Libia", nameEn: "Libya", region: "África" },
  { code: "MA", code3: "MAR", name: "Marruecos", nameEn: "Morocco", region: "África" },
  { code: "MG", code3: "MDG", name: "Madagascar", nameEn: "Madagascar", region: "África" },
  { code: "MZ", code3: "MOZ", name: "Mozambique", nameEn: "Mozambique", region: "África" },
  { code: "NG", code3: "NGA", name: "Nigeria", nameEn: "Nigeria", region: "África" },
  { code: "SN", code3: "SEN", name: "Senegal", nameEn: "Senegal", region: "África" },
  { code: "TN", code3: "TUN", name: "Túnez", nameEn: "Tunisia", region: "África" },
  { code: "TZ", code3: "TZA", name: "Tanzania", nameEn: "Tanzania", region: "África" },
  { code: "ZA", code3: "ZAF", name: "Sudáfrica", nameEn: "South Africa", region: "África" },
  { code: "ZW", code3: "ZWE", name: "Zimbabue", nameEn: "Zimbabwe", region: "África" },
  // Oceanía
  { code: "AU", code3: "AUS", name: "Australia", nameEn: "Australia", region: "Oceanía" },
  { code: "FJ", code3: "FJI", name: "Fiyi", nameEn: "Fiji", region: "Oceanía" },
  { code: "NZ", code3: "NZL", name: "Nueva Zelanda", nameEn: "New Zealand", region: "Oceanía" },
  { code: "PG", code3: "PNG", name: "Papúa Nueva Guinea", nameEn: "Papua New Guinea", region: "Oceanía" },
];

export function countryName(code: string): string {
  return MASTER_COUNTRIES.find((c) => c.code === code)?.name ?? code;
}
